
spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: ${spring.cloud.nacos.config.server-addr}
      #        namespace: ${spring.cloud.nacos.config.namespace}
      #        group: ${spring.cloud.nacos.config.group}
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

