server:
  port: 8888

spring:
  application:
    version: 1.0.0
  profiles:
    active: nacos-dev
  redis:
    host: redis.bigbang.local
    port: 6379
    database: 2
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin.bigbang.local:9411
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      token-validator:
        mode: jwt
        jwt-public-key-location: key/rsa_id.pub
      white-list:
        - aaa
        - bbb
        - ccc
      discovery:
        locator:
          lower-case-sehttpclientrvice-id: true

ribbon:
  eager-load:
    enabled: false



#sentinel:
#  transport:
#    port: 9001
#    dashboard: sentinel-dashboard.bigbang.internal:9999
#    eager: true


