server:
  port: 8080

spring:
  application:
    version: 1.0.0
  profiles:
    active: nacos-dev
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin.bigbang.local:9411
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      token-validator:
        mode: jwt
        jwt:
#          jws-algorithm: RSA
          public-key: 5c5f1b818a1363ef49f0fbc7b35a22c63cdb8a3b
      white-list:
        - aaa
        - bbb
        - ccc
      discovery:
        locator:
          lower-case-sehttpclientrvice-id: true

ribbon:
  eager-load:
    enabled: false



#sentinel:
#  transport:
#    port: 9001
#    dashboard: sentinel-dashboard.bigbang.internal:9999
#    eager: true


