server:
  port: 8080

spring:
#  application:
#    version: 1.0.0
#  redis:
#    host: redis.djtgroup.local
#    port: 6379
#    database: 5
#    password: 123qwe
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin.bigbang.local:9411
  cloud:
    discovery:
      platform: istio
      locator:
        lower-case-sehttpclientrvice-id: true
    loadbalancer:
      retry:
        enabled: true
    gateway:
      token-validator:
        enabled: true
#        mode: redis
        mode: mock
#        mode: jwt
#        public-key-location: keystore/rsa_id.pub
      app-validator:
        enabled: false
        signature:
          enabled: true
          verifierKeyMapping: "{\
            'key1': 'IayHU5eTYw9QMsThW7UZiu6p',\
            'key2': 'ki7DfjbKtuGf6f4HvWS0ukl9'\
          }"
      merchant-validator:
        enabled: false
        signature:
          enabled: true
        authentication:
          enabled: true


ribbon:
  eager-load:
    enabled: false

#sentinel:
#  transport:
#    port: 9001
#    dashboard: sentinel-dashboard.bigbang.internal:9999
#    eager: true


