spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bigbang_oauth2?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: bigbang
      password: bigbang
      initial-size: 10
      min-idle: 10
      max-active: 50
  redis:
    host: 127.0.0.1
    database: 1

eureka:
  client:
    service-url:
      defaultZone: http://reg1.bigbang.internal:8761/eureka/,reg2.bigbang.internal:8761/eureka/,reg3.bigbang.internal:8761/eureka/

zookeeper:
  server-list: zk1.bigang.internal:2181,zk2.bigang.internal:2181,zk3.bigang.internal:2181

management:
  server:
    port: 9090