server:
  port: 8085

spring:
  application:
    version: 1.0.0
  profiles:
    active: nacos-dev
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin.bigbang.local:9411






