spring:
  cloud:
    nacos:
      discovery:
        metadata:
          version: 1.0.0-SNAPSHOT
        server-addr: ${spring.cloud.nacos.config.server-addr}
      #        namespace: ${spring.cloud.nacos.config.namespace}
      #        group: ${spring.cloud.nacos.config.group}


